// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SogeVet.Server.Data;

#nullable disable

namespace SogeVet.Server.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240313145413_modificationSeedVraiURL")]
    partial class modificationSeedVraiURL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SogeVet.Server.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Homme"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Femme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Enfant"
                        });
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Adress 1",
                            Status = "En attente de traitement",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Address = "Adress 2",
                            Status = "En attente de traitement",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Address = "Adress 3",
                            Status = "En attente de traitement",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Adress 4",
                            Status = "En attente de traitement",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "Adress 5",
                            Status = "En attente de traitement",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SogeVet.Server.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 20f
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 3,
                            UnitPrice = 25.5f
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 4,
                            UnitPrice = 26f
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 10,
                            UnitPrice = 5.99f
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 80f
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 1,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 5f
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 40f
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 12,
                            Quantity = 2,
                            UnitPrice = 15.5f
                        });
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "Bleu",
                            Description = "Veste Bleu costard",
                            Images = "[\"https://www.angledelamode.com/public/img/big/IMG9218jpeg_6436b12ec91ee.jpeg\",\"https://mobile.yoox.com/images/items/49/49867134XU_14_f.jpg?impolicy=crop\\u0026width=387\\u0026height=490\",\"https://static.fursac.com/data/cache/LandingPage/picture/main/f/f/306.1606245987.jpg\"]",
                            Name = "Veste Bleu",
                            Quantity = 10,
                            Size = 30,
                            UnitPrice = 20.5f
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Jaune",
                            Description = "Robe jaune avec pois",
                            Images = "[\"https://www.tendance-retro.fr/cdn/shop/products/robe-jaune-a-pois-style-pin-up-284_1200x1200.jpg?v=1657442970\",\"https://robe-fleurie.fr/cdn/shop/products/H9158b11ff7f7490d9163393b8e0fdd522_1500x1500.jpg?v=1655929435\",\"https://www.oksana-mukha.fr/wp-content/uploads/2021/05/robe-de-cocktail-jaune-vif.jpg\"]",
                            Name = "Robe Jaune",
                            Quantity = 12,
                            Size = 41,
                            UnitPrice = 19.58f
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Rouge",
                            Description = "Description du produit 3",
                            Images = "[\"https://www.sao-bio.fr/6260-large_default/short-bebe-coton-bio-rayures-bleues.jpg\",\"https://www.saisondesabeilles.fr/wp-content/uploads/Saison-des-Abeilles-Vetements-enfants-Habillement-bebe-coton-biologique-garcon-fille-short-bleu-fonce1.jpg\"]",
                            Name = "Short Bleu",
                            Quantity = 40,
                            Size = 52,
                            UnitPrice = 10.2f
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Color = "Vert",
                            Description = "Description du produit 4",
                            Images = "[\"https://www.tee-shirt-publicitaire-pro.com/images/tee-shirt-publicitaire/large/t-shirt-publicitaire-fotoco-pour-enfant-vert_kelly_2.jpg\",\"https://www.ekinsport.com/media/catalog/product/cache/173ef9ab000c6667578594f63bf9da15/c/z/cz0909-302_t-shirt-nike-team-club-20-vert-pour-enfant-cz0909-302_01.jpg\",\"https://www.crafters.fr/images/stories/virtuemart/tt2016/PS_GI5000B_IRISHGREEN.jpg\"]",
                            Name = "t shirt enfant vert",
                            Quantity = 60,
                            Size = 32,
                            UnitPrice = 40.5f
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Color = "Violet",
                            Description = "Description du produit 5",
                            Images = "[\"https://www.basket-sucy.fr/wp-content/uploads/2022/09/des-petit-hauts-tee-shirt-frizon-violet-violet-t-shirts-tops-femme.jpg\",\"https://www.lagentlefactory.com/img/p/1/1/3/0/8/11308-medium_default.jpg\"]",
                            Name = "tshirt femme violet",
                            Quantity = 100,
                            Size = 36,
                            UnitPrice = 1.58f
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Color = "Vert",
                            Description = "Description du produit 6",
                            Images = "[\"https://image1.superdry.com/static/images/optimised/zoom/upload9223368955666328142.jpg\",\"https://images.asos-media.com/products/selected-homme-pantalon-cargo-vert-fonce/12511990-4?$n_640w$\\u0026wid=513\\u0026fit=constrain\",\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCQAO8ogt8GohpJASx9VtsSwr8_HgHFKFPV25Z5TQ3WA\\u0026s\",\"https://www.boutique-militaire.fr/cdn/shop/products/pantalon-cargo-vert-kaki-homme-boutique-militaire_600x600.jpg?v=1650033892\"]",
                            Name = "pantalon homme cargo",
                            Quantity = 2,
                            Size = 38,
                            UnitPrice = 3.22f
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Color = "Noir",
                            Description = "Description du produit 7",
                            Images = "[\"https://www.cdiscount.com/pdt2/6/4/4/3/700x700/mp135295644/rw/pull-femme-en-tricot-col-v-avec-boutons-manches-lo.jpg\",\"https://www.cdiscount.com/pdt2/5/0/6/1/700x700/mp128602506/rw/pull-femme-en-tricot-court-col-arrondi-manches-lon.jpg\",\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw9Ai1-uVO7dPC98wUI9hKs59CA7q4PHsnZrCEii3nwg\\u0026s\"]",
                            Name = "pull femme hiver noir",
                            Quantity = 12,
                            Size = 20,
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Color = "Bleu",
                            Description = "Description du produit 8",
                            Images = "[\"https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F30%2F93%2F30930506ba1409bdaf7eeddbeed199f7ac5b1783.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bkids_boys_clothing_jumperssweatshirts_hoodies%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D\\u0026call=url[file:/product/main]\",\"https://www.brise-lames.com/3452-large_default/gilet-capuche-en-molleton-raye-ecrumarine-enfant.jpg\"]",
                            Name = "Veste enfant rayé",
                            Quantity = 13,
                            Size = 27,
                            UnitPrice = 10.58f
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Color = "Bleu",
                            Description = "Description du produit 9",
                            Images = "[\"https://www.americanvintage-store.com/dw/image/v2/BGNV_PRD/on/demandware.static/-/Sites-master-catalog/default/dw8bf99e72/images/productPictures/E23/MODU09AE23/MODU09AE23-RAYBLEU-MODEL-4-large.jpg?sw=720\\u0026sh=1125\",\"https://cdn.monsieurtshirt.com/images/87908/product_list/filgood-l-homme-ideal-cocarde-brode.jpg?1627899944000\"]",
                            Name = "Short de bain rayé homme",
                            Quantity = 24,
                            Size = 25,
                            UnitPrice = 6.2f
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Color = "Jaune",
                            Description = "Description du produit 10",
                            Images = "[\"https://www.petitspinpins.com/1997-large_default/bavoir-bebe-raton-laveur-jaune.jpg\",\"https://www.ludilabel.fr/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/p/a/packshot-bavoir-trixie-mr-lion-bib.jpg\"]",
                            Name = "Bavoir bébé",
                            Quantity = 52,
                            Size = 8,
                            UnitPrice = 79.99f
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Color = "Marron",
                            Description = "Description du produit 11",
                            Images = "[\"https://cdn1.incorio.com/3034-large_default/chaussettes-fil-decosse-marron.jpg\",\"https://www.boulevard-dore.fr/44840-large_default/chaussettes-homme-soft-cotton-marron.jpg\"]",
                            Name = "Chaussettes marron",
                            Quantity = 62,
                            Size = 10,
                            UnitPrice = 19.58f
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Color = "Noir",
                            Description = "Description du produit 12",
                            Images = "[\"https://www.cdiscount.com/pdt2/9/2/5/1/700x700/mp61405925/rw/collant-femme-hiver-thermiques-collan-double-polai.jpg\",\"https://www.collantfemme.fr/355-large_default/collant-noir-fantaisie-fleuri-mila.jpg\",\"https://jambissima.fr/media/cache/w_500/6d/71/3a0b95e82b4318056b84ba521639.jpg\"]",
                            Name = "Collant Femme",
                            Quantity = 5,
                            Size = 30,
                            UnitPrice = 3.22f
                        });
                });

            modelBuilder.Entity("SogeVet.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "addressadmin1",
                            Email = "MailAdmin1",
                            FirstName = "Admin1",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Admin1L",
                            Password = "PasswordAdmin1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "addressadmin2",
                            Email = "MailAdmin2",
                            FirstName = "Admin2",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Admin2L",
                            Password = "PasswordAdmin2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "addressUser1",
                            Email = "MailUser1",
                            FirstName = "User1",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "User1L",
                            Password = "PasswordUser1"
                        },
                        new
                        {
                            Id = 4,
                            Address = "addressUser2",
                            Email = "MailUser2",
                            FirstName = "User2",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "User2L",
                            Password = "PasswordUser2"
                        },
                        new
                        {
                            Id = 5,
                            Address = "addressUser3",
                            Email = "MailUser3",
                            FirstName = "User3",
                            IsActive = true,
                            IsAdmin = false,
                            LastName = "User3L",
                            Password = "PasswordUser3"
                        });
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Order", b =>
                {
                    b.HasOne("SogeVet.Server.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SogeVet.Server.Entities.OrderItem", b =>
                {
                    b.HasOne("SogeVet.Server.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SogeVet.Server.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Product", b =>
                {
                    b.HasOne("SogeVet.Server.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SogeVet.Server.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SogeVet.Server.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
